<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>User registration Notification</title>
</head>

<body bgcolor="#8d8e90">
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
    <tr>
        <td><table width="600" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" align="center">
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="10%">&nbsp;</td>
                                <td width="80%" align="center" valign="top"><p><font style="font-family: Georgia, 'Times New Roman', Times, serif; color:#010101; font-size:24px"><strong><em>Hi {{$name}},</em></strong></font><br /><br />
                                        <font style=" line-height:21px">Welcome to Bank (M) PLC Service Portal.This automated email is to inform you that you have successful registered to use portal. The portal facilitate daily operation and communication to all Bank branches, department and units.</font></p>
                                    <p><font style="line-height:21px"><center>To access the portal use the bellow credentials. </center><br/> <br/>
                                            <center>USERNAME: <strong>{{$username}}</strong>. </center><br/>
                                            <center>PASSWORD: <strong>{{$password}}</strong>.</center><br/><br/>
                                            <center>
                                                <a href="{{url('login')}}">CLICK HERE TO LOGIN TO PORTAL</a>
                                            </center><br/><br/>
                                            You will not be able to login into the system untill your account is ACTIVATED, Please Contact ICT Department to ACTIVATE Your Account</br>
                                            For any further queries please contact or write to support. This is an autogenerated mail please do not reply, for any queries regarding support portal please write to support@bankm.com</font></p></td>
                                <td width="10%">&nbsp;</td>
                            </tr>
                        </table></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
            </table></td>
    </tr>
</table>
</body>
</html>
